name: Deploy to Local

 

on:
  push:
    branches:
      - main

 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if folder exists
        run: |
          if (Test-Path -Path "C:\laragon\www\studio4-chatbot-project" -PathType Container) {  Remove-Item -Path "C:\laragon\www\studio4-chatbot-project"   -Recurse -Force}

 

      - name: Deploy to Local
        run: cp -r ${{ github.workspace }} C:\laragon\www\studio4-chatbot-project



 

        
  build:
    runs-on: self-hosted

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: secret_key
        run: setx API_KEY ${{ secrets.API_KEY }}
